### PR TITLE
Removing erroneous CONTROL_N_PROVINCES_INCLUDING objective type. 

### PR DESCRIPTION
**Pull request by Mjb141**
Requires replacing with CONTROL_N_REGIONS_FROM

### CODE REVIEW

**Comment by Mjb141** [comment]
@OhManTFE We need to come up with regions to replace each of these lords' objectives - they were originally provinces but the key doesn't exist: https://github.com/msolefonte/vco/issues/171

The table `db/region_to_province_junctions_tables` maps provinces to regions and might be helpful.

I'll modify the documentation once we have the regions picked.

**Comment by OhManTFE** [comment]
Just use the regions instead of the provinces. All of them. Then subtract 8 regions from the total required number of regions. Eg. 36 out of 44 regions required.

**Comment by Mjb141** [comment]
So we could just make it N out of N and keep the old objective type? I'd rather do that...

**Comment by OhManTFE** [comment]
Sure can

**Pull request closed without merging**
