### PR TITLE
Add design for Exiles of Khorne

### PR DESCRIPTION
**Pull request by Mjb141**
# Khorne

## Skarbrand - Exiles of Khorne

* **Route I - The Great Game**
  * During times of utter destruction and murder, Khorne's bellows resound in the Chaos Wastes, causing madness in any that might hear. Of all the Ruinous Powers, Khorne is the biggest instigator of war and destruction. He will not rest until all the world is drowned in fire and blood.
  * Achieve the highest corruption in a minimum of 100 regions.
  * Reach Level 40 with Skarbrand (script_key: `vco_kho_exiles_of_khorne_skarbrand_rank`)
  * **Reward**:
    * _Khorne Ascendant_: 25% upkeep reduction for Bloodletters, Flesh Hounds of Khorne, Chaos Furies (Khorne), Exalted Bloodletters, Bloodcrushers, Bloodthirsters (effect_key: `wh3_dlc20_effect_upkeep_kho_daemons`), +8% replenishment (all armies)
_Reward flavour text:_ The world is in flames, broken and crumbling. The Exile has served his purpose.
khorne_points.png

* **Route II - Blood for the Blood God**
  * To the east is Lahmia, the Cursed City, birthplace of the vampires. Let their tainted blood drench the desert sands. To the south are great champions of order whose deaths will doubtless please Khorne greatly. Let there be blood.
  * Win 64 battles
  * Raze or Conquer the following settlements:
    * Lahmia
  * Destroy factions:
    * Last Defenders, Loremasters of Hoeth
  * **Reward**:
    * _The Reaping_: Blood Hosts +1 turn before attrition (effect_key: wh3_main_effect_force_khorne_bloodthirst_attrition_immunity), Blood Hosts +1 guaranteed Bloodthirster (effect_key: wh3_main_effect_kho_spawned_armies_guaranteed_bloodthirster)
_Reward flavour text:_ Skarbrand's Blood Hosts sweep across the land, drowning the mortal civilisations in blood.
wh2_dlc13_unit_abilities_bathed_in_blood.png

* **Route III - Skulls for the Skull Throne**
  * Within the dunes of Araby lie Tomb Kings and holy crusaders who stand against you. Their skulls will make a mighty offering to your hateful god.
  * Earn 8888 skulls (script_key: `vco_kho_exiles_of_khorne_skulls_earned`)
  * Destroy factions:
    * Khemri, Followers of Nagash, Chevaliers de Lyonesse, Cult of Sigmar
  * **Reward**:
    * _Skulls of the Desert_: Skulls earned from battle +50% (effect_key: `wh3_main_effect_kho_post_battle_skull_income`), Passive "Hellblade" for all Bloodletters and Bloodthirsters
_Reward flavour text:_ Khorne sits resplendent in his rage upon his throne, pleased with your offering. But, of course, he is never satisfied. He demands more. More! MORE!
bullet_kho_skull_piles.png

### CODE REVIEW

**Comment by Mjb141** [comment]
@OhManTFE Could do with some help/ideas on this, especially rewards. Skarbrand is kinda one-dimensional like Taurox, makes it tougher to come up interesting and useful rewards.

**Comment by Mjb141** [comment]
Note to self: unit codes for daemonic units:
wh3_main_kho_inf_bloodletters_0
wh3_main_kho_inf_bloodletters_1
wh3_main_kho_inf_bloodletters_summoned_0

wh3_main_kho_inf_flesh_hounds_of_khorne_0

wh3_main_kho_inf_chaos_furies_0

wh3_main_kho_mon_bloodthirster_0
wh3_main_kho_mon_bloodthirster_summoned_0

wh3_main_kho_cha_bloodreaper_0
wh3_main_kho_cha_bloodreaper_1
wh3_main_kho_cha_bloodreaper_2

**Comment by OhManTFE** [comment]
I have concerns with basically, the fundamental game design philosophy. Like, what are we trying to do with this mod?

My thinking is with routes, the whole point is we're trying to push players into certain directions. We're giving them goals and something to work towards, and three distinct goals at that.

See this image:
https://i.imgur.com/S5GY8SE.jpg

That was my initial thinking in the rough draft. You have three campaigns to choose from, which send the player off on completely different journeys with completely different foes, and each was loosely based on key Khorne themes

Ruin - fighting Skaven Greenskins and optionally Beastmen. Destroying the capital of the Dwarf Empire, Karaz-a-Karak. A massive blow to the realms of order.
Bone - collecting skulls of Tomb Kings, perhaps Bretonnians, Elves and Empire as well.
Blood - razing Lahmia and its blood-sucking vampire inhabitants, spilling the blood of Lizardmen, High Elves, and perhaps Dwarfs.

Then rewards would be based around those themes as well.

Now, with your ideas, what exactly are we asking the player to do?
Route I - own 60 units, complete the quest battle. Now, if you think about it, if you really boil that down. This objective basically is just "play the game however you want." It doesn't push the player in any specific direction. No player is going to deliberately ignore that quest battle. And amassing three 20 stacks is just something that would eventually happen as you played. It has no direction. See what I mean?

Route II - nothing inherently wrong with it, but look at these locations. The Empire, Slaaneshi factions in Ulthuan and Norsca. These targets are so far away. I thought we were aiming for more bite-sized campaigns. Route II as it is designed right now is probably going to be something like 200 turns!

Route III - same gripes as route 1. It just boils down to "play the game however you want". There's no direction. Player has nothing to work towards other than making a number go up.

We just need to ask ourselves what are routes? What do we want routes to be?

**Comment by Mjb141** [comment]
You're right and that's excellent feedback, thank you! 

The difficulty with Exiles of Khorne is that Skarbrand doesn't have 'rivals' (excluding a very limited rivalry with Slaaneshi factions that's based on very little beyond "they kill for other reasons than pride") or 'aims'. He doesn't have much of a story beyond raging destruction after being manipulated and cast out. If you look at CA's objectives they're basically subsets of the above - do the quest, sack/raze a lot, kill slaaneshi faction. Skarbrand is just _that_ narratively blank. So, for your Ruin/Bone/Blood routes, they're essentially just random factions. Skarbrand has no theme or story related to them, we're just picking a direction and saying "destroy these because they're here". I tried to minimise that as much as possible.

There's also the complication that Skarbrand's starting area is trash for his mechanics and intended gameplay. The common knowledge approach to his campaign is ditch his starting location as soon as the first cult pops up. If we build three routes in three directions from a garbage start location we're not doing anyone any favours, and we're massively limiting the point of his cult building teleport, which is to open Skarbrand up to more areas to raze. Focusing on his starting region like this image suggests and limiting that cult building teleport in such a way would be mistakes. Skarbrand just isn't meant to play around an area like a lot of factions are.

To put an example on this, in my legendary Skarbrand campaign I didn't even take the first settlement. I killed the immediate army on turn 1, ran north to the mountains (because they're clustered-up settlements for his movement refreshes), razed those, teleported to the chaos wastes when a cult popped up, fought/razed slaaneshi minor factions and Sigvald, then crossed south to norscan lands. That sort of movement is a necessary part of his campaign or you simply run out of places to sack/raze and not waste his mechanic.

> We just need to ask ourselves what are routes? What do we want routes to be?

In answer to this, while I absolutely accept your feedback is valid, that we want routes to be more directed, and we'll need to make changes to the objectives, Exiles of Khorne more than most/any faction will probably have to have some routes that are, when boiled down, "play the game however you want in a Khornate manner". I'd suggest we allow route 3 to be that and leave it unchanged, or limited changes.

Now, onto what can be improved. I'd suggest we start with:

* Route 1: Overhauled/replaced entirely
  * Own 60 units goes, to be replaced entirely.
  * Slaughter & Carnage mission replaced entirely.
* Route 2: Scope reduced to better fit the 50-70 turn ideal.
  * Destroy 1 faction of each race goes, to be replaced entirely.

Does that sound like a good start/compromise @OhManTFE ?

**Comment by OhManTFE** [comment]
True, I forgot about that cult teleport building. I played legendary Realms of Chaos and only used it at the very end of the game to teleport to Kislev. But if in this situation giving specific objectives actually limits the player we can remove it.

Could make route 1 be The Great Game, unlock all those rites. Could still have 60 and Skarband quest in ther as well if you wanted them real bad.

Route 2 with teleporting it could be quicker. Problem is cults are kind of random where they spawn at the moment. I don't know how to do destroy 1 from a following faction, that isn't currently something that exists at the moment.

**Comment by Mjb141** [comment]
I'm indifferent to the own 60 units and the quest objective. 

The aim with the quest objective was to do something with one of very few story-based objectives Skarbrand has (retrieve his weapons). 

The own 60 units was because Skarbrand can only really do that by sacking and razing constantly, either with bloodhosts or his own armies. You can't fund those armies with buildings like most factions, his building income generation is low, and his garrisons are so weak AI sack them often.

I definitely get that neither are very good for what we typically aim for as routes though.

>True, I forgot about that cult teleport building. I played legendary Realms of Chaos and only used it at the very end of the game to teleport to Kislev. But if in this situation giving specific objectives actually limits the player we can remove it.

This was less necessary in RoC because his start position was less terrible. His start in IE is downright awful, the settlements are so spread apart it's simply impossible to get raze chains going, or do much with bloodhosts before attrition. Leaving with cult buildings is pretty much always the best option, definitely don't want to restrict that.

Route 3 I think is sufficiently open-ended and Skarbrand-y that I'd like to leave that as-is.

>I don't know how to do destroy 1 from a following faction, that isn't currently something that exists at the moment.

Use the existing DESTROY_FACTION type, total 1, list of factions given. Use one of those per each race. But I'm not particularly attached to this objective, if we can come up with better ones let's do so.

**Comment by Mjb141** [comment]
I've removed the parts I think we should do from scratch and left route 3 alone - I'd like that to stay, it's very applicable for Skarbrand, and it includes the "spread corruption in X regions" that @msolefonte wants on monogod factions.

**Comment by OhManTFE** [comment]
# Khorne

## Skarbrand - Exiles of Khorne

* **Route I - The Great Game**
  * OBJECTIVE FLAVOUR TEXT
  * Achieve the highest corruption in a minimum of 100 regions.
  * Reach Level 40 with Skarbrand (script_key: `vco_kho_exiles_of_khorne_skarbrand_rank`)
  * **Reward**:
    * _Khorne Ascendant_: 25% upkeep reduction for Bloodletters, Flesh Hounds of Khorne, Chaos Furies (Khorne), Exalted Bloodletters, Bloodcrushers, Bloodthirsters (effect_key: `wh3_dlc20_effect_upkeep_kho_daemons`), +8% replenishment (all armies)
_Reward flavour text:_ The world is in flames, broken and crumbling. The Exile has served his purpose.

* **Route II - Blood for the Blood God**
  * To the east is Lahmia, the Cursed City, birthplace of the vampires. Let their tainted blood drench the desert sands. To the south are great champions of order whose deaths will doubtless please Khorne greatly. Let there be blood.
  * Summon 16 Blood Hosts - or if you want no-scripting required: Win 32 battles.
  * Raze or Conquer the following settlements:
    * Lahmia
  * Destroy factions:
    * Last Defenders, Loremasters of Hoeth
  * **Reward**:
    * _The Reaping_: Blood Hosts +1 turn before attrition (effect_key: wh3_main_effect_force_khorne_bloodthirst_attrition_immunity), Blood Hosts +1 guaranteed Bloodthirster (effect_key: wh3_main_effect_kho_spawned_armies_guaranteed_bloodthirster)
_Reward flavour text:_ Skarbrand's Blood Hosts sweep across the land, drowning the mortal civilisations in blood.

* **Route III - Skulls for the Skull Throne**
  * Within the dunes of Araby lie Tomb Kings and holy crusaders who stand against you. Their skulls will make a mighty offering to your hateful god.
  * Earn 8888 skulls (script_key: `vco_kho_exiles_of_khorne_skulls_earned`)
  * Destroy factions:
    * Khemri, Followers of Nagash, Chevaliers de Lyonesse, Cult of Sigmar
  * **Reward**:
    * _Skulls of the Desert_: Skulls earned from battle +50% (effect_key: `wh3_main_effect_kho_post_battle_skull_income`), Passive "Hellblade" for all Bloodletters and Bloodthirsters
_Reward flavour text:_ Khorne sits resplendent in his rage upon his throne, pleased with your offering. But, of course, he is never satisfied. He demands more. More! MORE!

**Comment by msolefonte** [comment]
Damn, this is a long conversation. Regarding the important thing, the discussion about _what we want to achieve with this mod_: the point is that what we want to do does not really work well for all lords. 

Creating custom and tailored routes works fine for 85% of the roaster, but there are some lords that are so sandboxy that is impossible to give them some objectives without getting the feeling that we are limiting the player choice. With Taurox or Skarbrand (or Archaon) you do not want to target X city. You want blood, wherever it flows from. I think it is fine to respect their sandboxy nature as long as we keep it a particular thing for particular lords. 

In any case, this can be solved again using multiple routes: we can give them a first/main route focused on a more-freedom based experience and then give them specific targets for the other ones. I think the design that @OhManTFE posted yesterday is excellend and a perfect example of this. I would go with it apart from some minor notes.

**Comment by msolefonte** [comment]
Earn 8888 skulls -> Make it 88888, otherwise you will win in 5 turns. We have to use the total count (we already got an script for that) instead of a maximum. We want skulls to be used, not hoarded.

**Comment by msolefonte** [comment]
Also make all numbers multiples of 8 -> 1/2/4/8/16/24/32/40... I think it is fun and we already do something similar with skavens.

**Comment by msolefonte** [comment]
I would go with winning battles (Maybe 64 or even 80? 32 feels low for Skarbrand) instead of Blood Hosts, because that is something you can keep track of and does not depend on randomness.

**Comment by Mjb141** [comment]
> I would go with winning battles (Maybe 64 or even 80? 32 feels low for Skarbrand) instead of Blood Hosts, because that is something you can keep track of and does not depend on randomness.

I like this - blood host battles will count so it still inventivises using them.

**Comment by Mjb141** [comment]
> Earn 8888 skulls -> Make it 88888, otherwise you will win in 5 turns. We have to use the total count (we already got an script for that) instead of a maximum. We want skulls to be used, not hoarded.

At 1000 per race + ~75 per battle +n per turn 88888 will be a long objective but do-able.

**Comment by Mjb141** [comment]
I've spotted a potential problem with route 3... Earn 88,888 skulls ... Get +50% skulls from battle. By the time you've earned 88,888 you are _swimming_ in skulls, earning more from battle is pointless. This was applicable after 8,888 when you still need more, but not 8,888.

I'd suggest that part of the reward is replaced?

**Comment by OhManTFE** [comment]
Yall created a problem that didn't exist with the skull reward by boosting to 80k. Just leave it at 8k and then the reward is still appreciated.

Doesn't matter if they get 8k quick because the objective still won't be completed until they destroy the four factions.

**Comment by OhManTFE** [comment]
khorne_points
khorne_skulls_bundle
wh2_dlc13_unit_abilities_bathed_in_blood
Icons attached.

**Pull request merged**
